### ISSUE TITLE
create github action configuration to build Windows and OSX packages for each tag

### ISSUE THREAD

**Issue by eroux** [buda-base/tibetan-ocr-app#14]
I currently have a totally untested `action.yml`

```
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          windows-console-mode: disable
          enable-plugins: pyside6
          script-name: main.py
          windows-console-mode: disable
          windows-icon-from-ico: logo.ico
          macos-app-icon: logo.icns
          macos-signed-app-name: io.bdrc.ocrapp
          macos-app-name: BDRC Tibetan OCR
          macos-app-version: 0.1
          include-data-dir: |
            ./Resources/Models=Resources/Models
            ./Resources/Assets=Resources/Assets
          mode: standalone

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
```

if possible (which it might not be) it will also build a package for Intel Mac
